version: '3'
services:
    orders-nodes-1:
        container_name: orders-nodes-1
        hostname: orders-nodes-1
        working_dir: /app
        build:
            context: .
            dockerfile: Mongo.Dockerfile
        image: orders-nodes-1
        env_file:
        - env/mongo.env
        - env/addresses.env
        volumes:
        - ./orders:/app/orders
        - ./common:/app/orders/common
        command: bash -c "cd orders/common/ && bash execution.sh 1"
        ports:
        - 1102:2801
        networks:
            shared_net:
                ipv4_address: 192.168.124.10
    payment-nodes-1:
        container_name: payment-nodes-1
        hostname: payment-nodes-1
        working_dir: /app
        build:
            context: .
            dockerfile: Mongo.Dockerfile
        image: payment-nodes-1
        env_file:
        - env/mongo.env
        - env/addresses.env
        volumes:
        - ./payment:/app/payment
        - ./common:/app/payment/common
        command: bash -c "cd payment/common/ && bash execution.sh 1"
        ports:
        - 1103:2801
        networks:
            shared_net:
                ipv4_address: 192.168.124.30
    stock-nodes-1:
        container_name: stock-nodes-1
        hostname: stock-nodes-1
        working_dir: /app
        build:
            context: .
            dockerfile: Mongo.Dockerfile
        image: stock-nodes-1
        env_file:
        - env/mongo.env
        - env/addresses.env
        volumes:
        - ./stock:/app/stock
        - ./common:/app/stock/common
        command: bash -c "cd stock/common/ && bash execution.sh 1"
        ports:
        - 1104:2801
        networks:
            shared_net:
                ipv4_address: 192.168.124.50
    coordinator-orders-1:
        container_name: coordinator-orders-1
        hostname: coordinator-orders-1
        working_dir: /app
        build:
            context: .
            dockerfile: coordinator.Dockerfile
        image: coordinator-orders-1
        env_file:
        - env/mongo.env
        - env/addresses.env
        volumes:
        - ./coordinator:/app/coordinator
        - ./common:/app/coordinator/common
        command: bash -c "cd coordinator/common/ && bash execution.sh 1 ORDERS"
        ports:
        - 1105:2801
        - 8080:2802
        networks:
            shared_net:
                ipv4_address: 192.168.124.20
    coordinator-payment-1:
        container_name: coordinator-payment-1
        hostname: coordinator-payment-1
        working_dir: /app
        build:
            context: .
            dockerfile: coordinator.Dockerfile
        image: coordinator-payment-1
        env_file:
        - env/mongo.env
        - env/addresses.env
        volumes:
        - ./coordinator:/app/coordinator
        - ./common:/app/coordinator/common
        command: bash -c "cd coordinator/common/ && bash execution.sh 1 PAYMENT"
        ports:
        - 1106:2801
        - 8081:2802
        networks:
            shared_net:
                ipv4_address: 192.168.124.41
    coordinator-stock-1:
        container_name: coordinator-stock-1
        hostname: coordinator-stock-1
        working_dir: /app
        build:
            context: .
            dockerfile: coordinator.Dockerfile
        image: coordinator-stock-1
        env_file:
        - env/mongo.env
        - env/addresses.env
        volumes:
        - ./coordinator:/app/coordinator
        - ./common:/app/coordinator/common
        command: bash -c "cd coordinator/common/ && bash execution.sh 1 STOCK"
        ports:
        - 1107:2801
        - 8082:2802
        networks:
            shared_net:
                ipv4_address: 192.168.124.61
networks:
    shared_net:
        driver: bridge
        ipam:
            config:
            -   subnet: 192.168.124.0/24
